apiVersion: v1
kind: apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-voting-app
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mresult-app-pod
  template:
    metadata:
      labels:
        app: result-app-pod
    spec:
      containers:
      - name: result-app
        image: dockersamples/examplevotingapp_result
        resources:
        ports:
        - containerPort: 80