apiVersion: v1
kind: apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: demo-voting-app
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: voting-app-pod
  template:
    metadata:
      labels:
        app: voting-app-pod
    spec:
      containers:
      - name: vorting-app
        image: dockersamples/examplevotingapp_vote
        ports:
        - containerPort: 80